// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/audit': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/audit.get').default>>>>
    }
    '/api/admin/content/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/content/[id].delete').default>>>>
    }
    '/api/admin/reports': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/reports.get').default>>>>
    }
    '/api/admin/reports/:id/resolve': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/reports/[id]/resolve.post').default>>>>
    }
    '/api/admin/settings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/settings.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/settings.put').default>>>>
    }
    '/api/admin/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/stats.get').default>>>>
    }
    '/api/admin/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users.get').default>>>>
    }
    '/api/admin/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id].delete').default>>>>
    }
    '/api/admin/users/:id/role': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id]/role.put').default>>>>
    }
    '/api/admin/users/:id/status': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id]/status.put').default>>>>
    }
    '/api/communities/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communities/[slug].get').default>>>>
    }
    '/api/communities/:slug/bans': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communities/[slug]/bans.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communities/[slug]/bans.post').default>>>>
    }
    '/api/communities/:slug/bans/:userId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communities/[slug]/bans/[userId].delete').default>>>>
    }
    '/api/communities/:slug/invites': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communities/[slug]/invites.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communities/[slug]/invites.post').default>>>>
    }
    '/api/communities/:slug/join': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communities/[slug]/join.post').default>>>>
    }
    '/api/communities/:slug/leave': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communities/[slug]/leave.post').default>>>>
    }
    '/api/communities/:slug/members': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communities/[slug]/members.get').default>>>>
    }
    '/api/communities/:slug/members/:userId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communities/[slug]/members/[userId].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communities/[slug]/members/[userId].put').default>>>>
    }
    '/api/communities/:slug/posts/:postId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communities/[slug]/posts/[postId].delete').default>>>>
    }
    '/api/communities/:slug/posts/:postId/replies': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communities/[slug]/posts/[postId]/replies.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communities/[slug]/posts/[postId]/replies.post').default>>>>
    }
    '/api/communities/:slug/posts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communities/[slug]/posts/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communities/[slug]/posts/index.post').default>>>>
    }
    '/api/communities/:slug/share': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communities/[slug]/share.post').default>>>>
    }
    '/api/communities': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communities/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/communities/index.post').default>>>>
    }
    '/api/content/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[id].put').default>>>>
    }
    '/api/content/:id/publish': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[id]/publish.post').default>>>>
    }
    '/api/content/:id/view': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[id]/view.post').default>>>>
    }
    '/api/content/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[slug].get').default>>>>
    }
    '/api/content': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/index.post').default>>>>
    }
    '/api/docs/:siteSlug': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[siteSlug].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[siteSlug].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[siteSlug].put').default>>>>
    }
    '/api/docs/:siteSlug/nav': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[siteSlug]/nav.get').default>>>>
    }
    '/api/docs/:siteSlug/pages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[siteSlug]/pages.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[siteSlug]/pages.post').default>>>>
    }
    '/api/docs/:siteSlug/pages/:pageId': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[siteSlug]/pages/[pageId].put').default>>>>
    }
    '/api/docs/:siteSlug/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[siteSlug]/search.get').default>>>>
    }
    '/api/docs/:siteSlug/versions': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/[siteSlug]/versions.post').default>>>>
    }
    '/api/docs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/docs/index.post').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/learn/:slug': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug].put').default>>>>
    }
    '/api/learn/:slug/:lessonSlug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug]/[lessonSlug].get').default>>>>
    }
    '/api/learn/:slug/:lessonSlug/complete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug]/[lessonSlug]/complete.post').default>>>>
    }
    '/api/learn/:slug/enroll': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug]/enroll.post').default>>>>
    }
    '/api/learn/:slug/lessons': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug]/lessons.post').default>>>>
    }
    '/api/learn/:slug/modules': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug]/modules.post').default>>>>
    }
    '/api/learn/:slug/modules/:moduleId': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug]/modules/[moduleId].put').default>>>>
    }
    '/api/learn/:slug/publish': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug]/publish.post').default>>>>
    }
    '/api/learn/:slug/unenroll': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/[slug]/unenroll.post').default>>>>
    }
    '/api/learn/certificates': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/certificates.get').default>>>>
    }
    '/api/learn/enrollments': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/enrollments.get').default>>>>
    }
    '/api/learn': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learn/index.post').default>>>>
    }
    '/api/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/search.get').default>>>>
    }
    '/api/social/bookmark': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/social/bookmark.post').default>>>>
    }
    '/api/social/comments': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/social/comments.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/social/comments.post').default>>>>
    }
    '/api/social/comments/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/social/comments/[id].delete').default>>>>
    }
    '/api/social/like': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/social/like.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/social/like.post').default>>>>
    }
    '/api/users/:username': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[username].get').default>>>>
    }
    '/api/users/:username/content': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[username]/content.get').default>>>>
    }
    '/.well-known/nodeinfo': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/.well-known/nodeinfo').default>>>>
    }
    '/.well-known/webfinger': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/.well-known/webfinger').default>>>>
    }
    '/inbox': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/inbox').default>>>>
    }
    '/nodeinfo/2.1': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/nodeinfo/2.1').default>>>>
    }
    '/users/:username': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/users/[username]').default>>>>
    }
    '/users/:username/followers': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/users/[username]/followers').default>>>>
    }
    '/users/:username/following': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/users/[username]/following').default>>>>
    }
    '/users/:username/inbox': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/users/[username]/inbox').default>>>>
    }
    '/users/:username/outbox': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/users/[username]/outbox').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+nitro-server@3.21.1_db0@0.3.4_drizzle-orm@0.38.4_kysely@0.28.11_pg@8.20.0___drizz_07dfe389c2ad4c703151522bdf7a8e92/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}