use std::fs;
use tempfile::TempDir;

#[test]
fn scaffold_copies_full_reference_app() {
    let tmp = TempDir::new().unwrap();

    let config = create_commonpub::prompts::InstanceConfig::with_defaults("test-instance");
    let result = create_commonpub::scaffold::create_instance_at(tmp.path(), "test-instance", &config);
    assert!(result.is_ok());

    let dir = tmp.path().join("test-instance");

    // Root config files (generated by scaffold)
    assert!(dir.join(".env").exists());
    assert!(dir.join("commonpub.config.ts").exists());
    assert!(dir.join("nuxt.config.ts").exists());
    assert!(dir.join("package.json").exists());
    assert!(dir.join("tsconfig.json").exists());
    assert!(dir.join("app.vue").exists());
    assert!(dir.join("docker-compose.yml").exists());
    assert!(dir.join(".gitignore").exists());
    assert!(dir.join("README.md").exists());
    assert!(dir.join("drizzle.config.ts").exists());

    // Full reference app structure (copied from embedded files)
    assert!(dir.join("pages/index.vue").exists());
    assert!(dir.join("pages/explore.vue").exists());
    assert!(dir.join("pages/feed.vue").exists());
    assert!(dir.join("pages/search.vue").exists());
    assert!(dir.join("pages/create.vue").exists());
    assert!(dir.join("pages/dashboard.vue").exists());
    assert!(dir.join("pages/hubs").exists());
    assert!(dir.join("pages/learn").exists());
    assert!(dir.join("pages/contests").exists());
    assert!(dir.join("pages/auth/login.vue").exists());
    assert!(dir.join("pages/settings").exists());

    // Full component library (copied)
    assert!(dir.join("components/ContentCard.vue").exists());
    assert!(dir.join("components/AuthorRow.vue").exists());
    assert!(dir.join("components/EngagementBar.vue").exists());
    assert!(dir.join("components/editors/BlockCanvas.vue").exists());
    assert!(dir.join("components/editors/ProjectEditor.vue").exists());
    assert!(dir.join("components/blocks").exists());

    // Full API routes (copied)
    assert!(dir.join("server/api/content").exists());
    assert!(dir.join("server/api/hubs").exists());
    assert!(dir.join("server/api/social").exists());
    assert!(dir.join("server/api/learn").exists());
    assert!(dir.join("server/api/admin").exists());
    assert!(dir.join("server/api/contests").exists());
    assert!(dir.join("server/api/health.get.ts").exists());

    // Server infrastructure (copied from reference app)
    assert!(dir.join("server/utils/config.ts").exists());
    assert!(dir.join("server/utils/db.ts").exists());
    assert!(dir.join("server/utils/auth.ts").exists());
    assert!(dir.join("server/utils/validate.ts").exists());
    assert!(dir.join("server/middleware/auth.ts").exists());
    assert!(dir.join("server/middleware/security.ts").exists());

    // Federation routes (copied)
    assert!(dir.join("server/routes/inbox.ts").exists());
    assert!(dir.join("server/routes/users").exists());

    // Federation pages and routes (copied)
    assert!(dir.join("pages/federation/index.vue").exists());
    assert!(dir.join("pages/federation/search.vue").exists());
    assert!(dir.join("pages/mirror").exists());
    assert!(dir.join("server/api/federation").exists());
    assert!(dir.join("server/api/admin/federation").exists());

    // Composables (copied)
    assert!(dir.join("composables/useAuth.ts").exists());
    assert!(dir.join("composables/useFeatures.ts").exists());
    assert!(dir.join("composables/useContentTypes.ts").exists());
    assert!(dir.join("composables/useBlockEditor.ts").exists());
    assert!(dir.join("composables/useContentSave.ts").exists());
    assert!(dir.join("composables/useFederation.ts").exists());
    assert!(dir.join("composables/usePublishValidation.ts").exists());

    // New components (copied)
    assert!(dir.join("components/ImageUpload.vue").exists());
    assert!(dir.join("components/ContentStarterForm.vue").exists());
    assert!(dir.join("components/FederatedContentCard.vue").exists());
    assert!(dir.join("components/PublishErrorsModal.vue").exists());
    assert!(dir.join("components/RemoteActorCard.vue").exists());
    assert!(dir.join("components/RemoteUserSearch.vue").exists());

    // Layouts (copied)
    assert!(dir.join("layouts/default.vue").exists());
    assert!(dir.join("layouts/editor.vue").exists());

    // Plugins (copied)
    assert!(dir.join("plugins/auth.ts").exists());

    // Excluded directories should NOT be present
    assert!(!dir.join("node_modules").exists());
    assert!(!dir.join(".nuxt").exists());
    assert!(!dir.join(".output").exists());
    assert!(!dir.join("__tests__").exists());
    assert!(!dir.join("e2e").exists());
    assert!(!dir.join("scripts").exists());
}

#[test]
fn scaffold_without_docker_skips_compose() {
    let tmp = TempDir::new().unwrap();

    let mut config = create_commonpub::prompts::InstanceConfig::with_defaults("no-docker");
    config.use_docker = false;
    let result = create_commonpub::scaffold::create_instance_at(tmp.path(), "no-docker", &config);
    assert!(result.is_ok());

    let dir = tmp.path().join("no-docker");
    assert!(dir.join(".env").exists());
    assert!(dir.join("nuxt.config.ts").exists());
    assert!(!dir.join("docker-compose.yml").exists());
}

#[test]
fn scaffold_fails_if_directory_exists() {
    let tmp = TempDir::new().unwrap();

    fs::create_dir(tmp.path().join("existing")).unwrap();
    let config = create_commonpub::prompts::InstanceConfig::with_defaults("existing");
    let result = create_commonpub::scaffold::create_instance_at(tmp.path(), "existing", &config);
    assert!(result.is_err());
}

#[test]
fn init_creates_files_in_current_dir() {
    let tmp = TempDir::new().unwrap();

    let config = create_commonpub::prompts::InstanceConfig::with_defaults("test");
    let result = create_commonpub::scaffold::init_instance_at(tmp.path(), &config);
    assert!(result.is_ok());

    // Generated config files
    assert!(tmp.path().join(".env").exists());
    assert!(tmp.path().join("commonpub.config.ts").exists());
    assert!(tmp.path().join("nuxt.config.ts").exists());

    // Copied reference app
    assert!(tmp.path().join("pages/index.vue").exists());
    assert!(tmp.path().join("server/api/health.get.ts").exists());
    assert!(tmp.path().join("components/ContentCard.vue").exists());
}

#[test]
fn generated_env_has_correct_values() {
    let config = create_commonpub::prompts::InstanceConfig::with_defaults("my-community");
    let env = create_commonpub::template::render_env(&config);

    assert!(env.contains("INSTANCE_NAME=my-community"));
    assert!(env.contains("INSTANCE_DOMAIN=my-community.localhost"));
    assert!(env.contains("FEATURE_CONTENT=true"));
    assert!(env.contains("FEATURE_HUBS=true"));
    assert!(env.contains("FEATURE_FEDERATION=false"));
    assert!(env.contains("EMAIL_ADAPTER=console"));
    assert!(env.contains("NUXT_DATABASE_URL="));
}

#[test]
fn generated_config_is_valid_structure() {
    let config = create_commonpub::prompts::InstanceConfig::with_defaults("my-community");
    let ts_config = create_commonpub::template::render_config(&config);

    assert!(ts_config.contains("defineCommonPubConfig"));
    assert!(ts_config.contains("name: 'my-community'"));
    assert!(ts_config.contains("emailPassword: true"));
}

#[test]
fn package_json_patched_correctly() {
    let tmp = TempDir::new().unwrap();
    let config = create_commonpub::prompts::InstanceConfig::with_defaults("patch-test");
    create_commonpub::scaffold::create_instance_at(tmp.path(), "patch-test", &config).unwrap();

    let dir = tmp.path().join("patch-test");
    let pkg = fs::read_to_string(dir.join("package.json")).unwrap();

    // workspace:* replaced with npm versions
    assert!(!pkg.contains("workspace:*"));
    assert!(pkg.contains("\"@commonpub/schema\": \"^0.8.2\""));
    assert!(pkg.contains("\"@commonpub/server\": \"^2.1.7\""));

    // Package renamed
    assert!(pkg.contains("\"patch-test\""));
    assert!(!pkg.contains("@commonpub/reference"));

    // Has @types/node
    assert!(pkg.contains("@types/node"));

    // Has drizzle-kit
    assert!(pkg.contains("drizzle-kit"));

    // All commonpub packages present (reference app includes all)
    assert!(pkg.contains("@commonpub/server"));
    assert!(pkg.contains("@commonpub/schema"));
    assert!(pkg.contains("@commonpub/auth"));
    assert!(pkg.contains("@commonpub/ui"));
    assert!(pkg.contains("@commonpub/config"));
}

#[test]
fn nuxt_config_patched_for_standalone() {
    let tmp = TempDir::new().unwrap();
    let mut config = create_commonpub::prompts::InstanceConfig::with_defaults("standalone-test");
    config.domain = "makers.example.com".to_string();
    config.name = "Makers Club".to_string();
    config.description = "A maker community".to_string();
    create_commonpub::scaffold::create_instance_at(tmp.path(), "standalone-test", &config).unwrap();

    let dir = tmp.path().join("standalone-test");
    let nuxt = fs::read_to_string(dir.join("nuxt.config.ts")).unwrap();

    // Monorepo paths removed
    assert!(!nuxt.contains("../../packages"));
    assert!(!nuxt.contains("fileURLToPath"));
    assert!(!nuxt.contains("uiTheme("));

    // npm package paths used instead
    assert!(nuxt.contains("'@commonpub/ui/theme/base.css'"));
    assert!(nuxt.contains("'@commonpub/ui/theme/dark.css'"));
    assert!(nuxt.contains("'@commonpub/ui/theme/components.css'"));

    // Instance config patched
    assert!(nuxt.contains("makers.example.com"));
    assert!(nuxt.contains("Makers Club"));
    assert!(nuxt.contains("A maker community"));

    // Vite fs.allow patched for standalone
    assert!(nuxt.contains("allow: ['..']"));
    assert!(!nuxt.contains("allow: ['../..']"));
}

#[test]
fn config_has_correct_feature_flags() {
    let tmp = TempDir::new().unwrap();
    let mut config = create_commonpub::prompts::InstanceConfig::with_defaults("flag-test");
    config.feature_contests = true;
    config.feature_admin = true;
    config.feature_federation = true;
    config.feature_docs = false;
    config.feature_learning = false;
    config.feature_video = false;
    config.content_types = vec!["project".to_string(), "blog".to_string()];
    config.contest_creation = "staff".to_string();
    create_commonpub::scaffold::create_instance_at(tmp.path(), "flag-test", &config).unwrap();

    let dir = tmp.path().join("flag-test");

    // commonpub.config.ts has correct flags
    let cpub_config = fs::read_to_string(dir.join("commonpub.config.ts")).unwrap();
    assert!(cpub_config.contains("contests: true"));
    assert!(cpub_config.contains("admin: true"));
    assert!(cpub_config.contains("federation: true"));
    assert!(cpub_config.contains("docs: false"));
    assert!(cpub_config.contains("learning: false"));
    assert!(cpub_config.contains("video: false"));
    assert!(cpub_config.contains("contestCreation: 'staff'"));
    assert!(cpub_config.contains("contentTypes: ['project', 'blog']"));

    // .env has matching flags
    let env = fs::read_to_string(dir.join(".env")).unwrap();
    assert!(env.contains("FEATURE_CONTESTS=true"));
    assert!(env.contains("FEATURE_ADMIN=true"));
    assert!(env.contains("FEATURE_FEDERATION=true"));
    assert!(env.contains("FEATURE_DOCS=false"));
    assert!(env.contains("FEATURE_LEARNING=false"));
    assert!(env.contains("FEATURE_VIDEO=false"));
}

#[test]
fn generated_server_infra_is_correct() {
    let tmp = TempDir::new().unwrap();
    let config = create_commonpub::prompts::InstanceConfig::with_defaults("my-site");
    create_commonpub::scaffold::create_instance_at(tmp.path(), "my-site", &config).unwrap();

    let dir = tmp.path().join("my-site");

    // Auth middleware uses configurable email adapter
    let auth_mw = fs::read_to_string(dir.join("server/middleware/auth.ts")).unwrap();
    assert!(auth_mw.contains("SmtpEmailAdapter"));
    assert!(auth_mw.contains("ResendEmailAdapter"));
    assert!(auth_mw.contains("ConsoleEmailAdapter"));

    // DB util has pool + singleton
    let db = fs::read_to_string(dir.join("server/utils/db.ts")).unwrap();
    assert!(db.contains("pg.Pool") || db.contains("Pool"));
    assert!(db.contains("useDB"));

    // Auth util has require/optional helpers
    let auth = fs::read_to_string(dir.join("server/utils/auth.ts")).unwrap();
    assert!(auth.contains("requireAuth"));
    assert!(auth.contains("requireAdmin"));
    assert!(auth.contains("getOptionalUser"));

    // Security middleware has rate limiting
    let sec = fs::read_to_string(dir.join("server/middleware/security.ts")).unwrap();
    assert!(sec.contains("RateLimitStore"));

    // Auth composable has full API
    let composable = fs::read_to_string(dir.join("composables/useAuth.ts")).unwrap();
    assert!(composable.contains("signIn"));
    assert!(composable.contains("signUp"));
    assert!(composable.contains("signOut"));
}

// ── CLI flags ─────────────────────────────────────────────

#[test]
fn cli_binary_with_feature_flags() {
    use assert_cmd::Command;

    let tmp = TempDir::new().unwrap();
    let name = "flag-test";

    Command::cargo_bin("create-commonpub")
        .unwrap()
        .current_dir(tmp.path())
        .args(&[
            "new", name,
            "--features", "content,social,hubs,contests,admin",
            "--content-types", "project,blog",
            "--contest-creation", "staff",
            "--no-docker",
        ])
        .assert()
        .success();

    let dir = tmp.path().join(name);

    // Docker skipped
    assert!(!dir.join("docker-compose.yml").exists());

    // Full reference app copied (all pages present regardless of flags)
    assert!(dir.join("pages/index.vue").exists());
    assert!(dir.join("pages/explore.vue").exists());
    assert!(dir.join("pages/hubs").exists());
    assert!(dir.join("pages/contests").exists());
    assert!(dir.join("server/api/content").exists());
    assert!(dir.join("components/ContentCard.vue").exists());

    // Config has correct feature flags
    let config = fs::read_to_string(dir.join("commonpub.config.ts")).unwrap();
    assert!(config.contains("content: true"));
    assert!(config.contains("hubs: true"));
    assert!(config.contains("contests: true"));
    assert!(config.contains("admin: true"));
    assert!(config.contains("docs: false"));
    assert!(config.contains("learning: false"));
    assert!(config.contains("video: false"));
    assert!(config.contains("contestCreation: 'staff'"));
    assert!(config.contains("contentTypes: ['project', 'blog']"));

    // .env has correct flags
    let env = fs::read_to_string(dir.join(".env")).unwrap();
    assert!(env.contains("FEATURE_CONTESTS=true"));
    assert!(env.contains("FEATURE_DOCS=false"));
    assert!(env.contains("FEATURE_LEARNING=false"));

    // Package.json patched
    let pkg = fs::read_to_string(dir.join("package.json")).unwrap();
    assert!(!pkg.contains("workspace:*"));
    assert!(pkg.contains("@commonpub/schema"));
    assert!(pkg.contains("@commonpub/server"));
}
